# Generated by Django 2.2 on 2021-02-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('CL', 'classes'), ('AP', 'About'), ('ST', 'Staff'), ('GA', 'Gallery')], max_length=10)),
                ('slug', models.SlugField(blank=True, default='')),
                ('description', models.TextField()),
                ('image', models.FileField(default='', upload_to='')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
