# Generated by Django 2.2 on 2021-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
